name: Scan code before building apk

on: [push]

jobs:
  scan-code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install bearer for code scaning
      run: |
        curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh

    - name: Run tests
      run: |
        cd bin
        ./bearer scan ../DamnVulnerableBank --output code-scan-results/result.json || { echo "Error: $?"; exit 1; }
