name: Scan code before building apk

on: [push]

jobs:
  scan-code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install bearer for code scaning
      run: |
        sudo apt-get install apt-transport-https
        echo "deb [trusted=yes] https://apt.fury.io/bearer/ /" | sudo tee -a /etc/apt/sources.list.d/fury.list
        sudo apt-get update
        sudo apt-get install bearer

    - name: Run tests1
      run: |
        pwd

    - name: Run tests2
      run: |
        ls -al
        
    - name: Run tests3
      run: |
        cd ..
        pwd
        
    - name: Run tests4
      run: |
        ls -al

    - name: Run tests
      run: |
        bearer scan DamnVulnerableBank --output code-scan-results/result.json
