name: Scan code before building apk

on: [push]

jobs:
  scan-code:
    runs-on: ubuntu-latest

    steps:
    - name: install insidersec for code scaning
      run: |
        wget https://github.com/insidersec/insider/releases/download/3.0.0/insider_3.0.0_linux_x86_64.tar.gz
        tar -xf insider_3.0.0_linux_x86_64.tar.gz 
        chmod +x insider
        ./insider --tech android --target .
